name: Benchmark Jarl

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update Jarl CSV
      working-directory: ./core
      run: lein perf-jarl

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Updating performance metrics
        title: Updating performance metrics
        body: Please do a "Rebase and merge", so the revision in the CSV stays relevant.
        signoff: true
        branch: opa-bench
        delete-branch: true
        branch-suffix: random
        base: main # Required for when triggered on tag push
