name: Benchmark OPA

on:
  workflow_dispatch:
    inputs:
      opa_version:
        description: OPA version
        required: true
        type: string

jobs:
  generate-metrics:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: ${{ inputs.opa_version }}

    - name: Update OPA CSV
      working-directory: ./core
      run: lein perf-opa

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Updating OPA ${{ inputs.opa_version }} performance metrics
        title: Updating OPA ${{ inputs.opa_version }} performance metrics
        body: Please do a "Rebase and merge", so the revision in the CSV stays relevant.
        signoff: true
        branch: bench
        delete-branch: true
        branch-suffix: short-commit-hash
