name: Check Code

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  clj-kondo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clj-kondo linter
      run: lein clj-kondo

  eastwood:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run eastwood linter
      run: lein eastwood

  kibit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run kibit linter
      run: lein kibit

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: lein test
