name: Check Code

on:
  push:
  workflow_dispatch:

jobs:
  clj-kondo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-lint-${{ hashFiles('project.clj') }}
        restore-keys: cljdeps-lint-
    - run: lein clj-kondo

  eastwood:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-lint-${{ hashFiles('project.clj') }}
        restore-keys: cljdeps-lint-
    - run: lein eastwood

  kibit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-lint-${{ hashFiles('project.clj') }}
        restore-keys: cljdeps-lint-
    - run: lein kibit

  test-clj:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-test-${{ hashFiles('project.clj') }}
        restore-keys: cljdeps-test-
    - run: lein gen-compliance :clj
    - run: lein test

  test-cljs-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-test-${{ hashFiles('project.clj') }}
        restore-keys: cljdeps-test-
    # Hack allowing compliance_tests.cljs to compile without generated tests
    - run: |
        mkdir -p src/test/cljs/compliance/generated
        echo "(ns test.compliance.generated.tests)" > src/test/cljs/compliance/generated/tests.cljs
    - run: lein cljsbuild once test
    - run: node target/cljs-test.js

  test-cljs-compliance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-test-${{ hashFiles('project.clj') }}
        restore-keys: cljdeps-test-
    - run: lein gen-compliance :cljs
    - run: lein cljsbuild once compliance
    - run: node target/cljs-compliance.js
